name: Run Bot (Self-triggering)

on:
  workflow_dispatch: # Allows manual start

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Chrome and dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot
        run: python url_monitor.py

      # Add delay before next trigger (5 minutes = 300 seconds)
      - name: Delay before next run
        run: sleep 500

      # Self-trigger next run
      - name: Trigger Next Run
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches" \
          -d '{"ref":"main"}'
