name: URL Monitor

on:
  schedule:
    - cron: '0 * * * *'  # Hourly checks
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Run URL monitor
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python url_monitor.py
      
    - name: Create Auto-Merging PR
      if: success() && fileExists('updated_url_list.txt')
      uses: peter-evans/create-pull-request@v4
      with:
        title: "Auto-update URL list"
        body: "Automatically updated URL list"
        branch: "auto-update-urls-$(date +%s)"
        commit-message: "Update URL list"
        delete-branch: true
        auto-merge: true
        auto-merge-method: merge
