name: URL Monitor

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Needed to create new branches
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests
        
    - name: Run URL monitor
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python url_monitor.py
      
    - name: Check for updated URL list
      id: check_file
      run: |
        if [ -f "updated_url_list.txt" ]; then
          echo "file_exists=true" >> $GITHUB_OUTPUT
        else
          echo "file_exists=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Create PR if there are changes
      if: steps.check_file.outputs.file_exists == 'true'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Rename the updated file
        mv updated_url_list.txt url_list.txt
        
        # Create timestamp-based branch name
        BRANCH_NAME="url-update-$(date +%s)"
        
        # Create and push to new branch
        git checkout -b $BRANCH_NAME
        git add url_list.txt
        git commit -m "Update URL list with new URLs"
        git push origin $BRANCH_NAME
        
        # Create pull request
        gh pr create \
          --title "Update URL list" \
          --body "Automated update of URL list with new URLs" \
          --head $BRANCH_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
